### YamlMime:ManagedReference
items:
- uid: Microsoft.ApplicationInsights
  commentId: N:Microsoft.ApplicationInsights
  id: Microsoft.ApplicationInsights
  children:
  - Microsoft.ApplicationInsights.TelemetryClient
  langs:
  - csharp
  - vb
  name: Microsoft.ApplicationInsights
  nameWithType: Microsoft.ApplicationInsights
  fullName: Microsoft.ApplicationInsights
  type: Namespace
  assemblies:
  - Microsoft.ApplicationInsights
references:
- uid: Microsoft.ApplicationInsights.TelemetryClient
  commentId: T:Microsoft.ApplicationInsights.TelemetryClient
  isExternal: false
  name: TelemetryClient
  nameWithType: TelemetryClient
  fullName: Microsoft.ApplicationInsights.TelemetryClient
